theia/package.json
theia/yarn.lock

Trying to bump Theia in baby steps

build(deps): remove resolutions

---

requirements.txt

- Upgrade numpy to version 1.22.0
- Upgrade notebook to version 6.4.12

build(deps): upgrade numpy and notebook

---

jupyterlab-python/Dockerfile
requirements.txt

While slightly scary to bump a major version, we have been upgrading "notebook", the library that deals with the actual notebooks, more regularly.

build(deps): bump JupyterLab from 2 to 3

---

theia/package.json
theia/yarn.lock

build(deps): bump minimatch

---

theia/package.json
theia/yarn.lock

build(deps): bump loader-utils

---

rstudio/rstudio-start.sh

The dynamic ones based on a person's team where missing specifically
DT-822

feat: pull all S3_* environment variables into RStudio

---

rstudio-rv4/Dockerfile
rstudio-rv4/exploretiva/DESCRIPTION
rstudio-rv4/exploretiva/NAMESPACE
rstudio-rv4/exploretiva/R/copy_explore_tiva.R
rstudio-rv4/exploretiva/inst/rstudio/templates/project/explore_tiva.dcf
rstudio-rv4/exploretiva/inst/templates/explore_tiva.R
rstudio-rv4/rstudio-db-creds.R
rstudio-rv4/rstudio-start.sh

The scope of this PR is to introduce a folder structure and setup for rstudio rv4. Upcoming PR's will address pointing the setup to version 4 along with fixing any breaking dependencies...

Add rstudio 4 folder structure

---

requirements.in
requirements.txt

removing jupyter-collaboration as it might be causing issues

removing jupyter-collaboration as it might be causing issues

---

s3sync/start.sh

This depends on https://github.com/uktrade/data-workspace/pull/61 having been applied, which it has

feat: log startup time to CloudWatch

---

requirements.txt

Reverts uktrade/data-workspace-tools#108

Revert "build(deps): bump sqlparse from 0.4.4 to 0.5.0"

---

vscode/Dockerfile
vscode/config.yaml
vscode/settings.json
vscode/start.sh

* vscode in tools
* R and python capable
* add data analysis/science extensions

feat: code-server (vscode fork) in tools

---

Dockerfile

The variables have to be set _after_ the locale has been generated

fix: locale generation

---

Dockerfile

Suspecting it makes them not be re-fetched and re-compiled, when I think we should

feat: don't have packages install on cran-binary-mirror image

---

mirrors-sync-cran-binary/build.R

To make it a touch easier to use from R

feat: add renv to CRAN binary mirror

---

Dockerfile
python-setup.sh

Now we use multi-stage builds to have a hierarchy

refactor: no need for python-setup script

---

pgadmin/start.sh
python-jupyterlab/start.sh
python-theia/start.sh

Minor optimisation + security enhancement (since less continues to run as root) that I suspect also forwards signals better

feat: use exec in more tools

---

python-theia/package.json
python-theia/yarn.lock

To hopefully allow less vulnerable deps

build(deps): bump Theia

---

Jenkinsfile

So we can iterate more quickly

ci: add (optional) caching to Jenkinsfile

---

Dockerfile
python-theia/package.json

So more easily found/changed if needed

refactor: move Theia build and download plugin steps to Dockerfile

---

python-theia/package.json
python-theia/start.sh
python-theia/yarn.lock

This hopefully properly restores Theia to
d4f602d0c9f54fe62f325b93833169acee4da1ff where it was working

fix: restore Theia to working version

---

private_package_index/create_index_html.py

update gitlab private pypi index script file, add more logging

update gitlab private pypi index script file, add more logging

---

private_package_index/create_index_html.py

disable regex while end-to-end test

disable regex while end-to-end test

---

private_package_index/create_index_html.py

correct full path for each file, to prepare index

correct full path for each file, to prepare index

---

private_package_index/create_index_html.py

have full https path for aws with bucket and prefix

have full https path for aws with bucket and prefix

---

private_package_index/create_index_html.py

refactor and simplify index creation script for Girlab private python index packages

refactor and simplify index creation script

---

Dockerfile
Jenkinsfile
python-vscode/start.sh

This adds VS Code via code-server, as a possible/hopeful replacement to Theia, that should be more maintainable and more desirable from our users.

feat: add VSCode via code-server

---

Dockerfile

In order to support the move to bookworm, we install s3sync and the dependencies for metrics via venv.
Technically we could extend from the python base image as for other applications, but that would increase the size of the container considerably because it has a lot of default Python packages installed in it, and so opting to keep it light.

refactor: s3sync and metrics installed via venv

---

Dockerfile

This activates conda more consistently for all Python images. Specifically it:
- Sets SHELL so that RUN statements in the Dockefile don't need to each activate the conda base environment.
- Sets ENTRYPOINT to use conda run so that the CMD always runs in a conda environment.
This is all for moving to bookworm where to install packages via pip, a virtual environment (like conda) _has_ to be present in general.
The above changes should mean that visualisations don't need to be changed - they can use python/pip as usual, and they will transparently just run in a conda environment.
This also does a few things along the way:
- Bumps the version of conda (slightly by the by, but felt should address any issues on a more recent conda than an older one that we will have to eventually move away …

feat: activate conda for Python images

---

python/requirements.in
python/requirements.txt

This PR adds pre-commit and boto3 into python based images for further use

adding pre-commit and boto3 to python base image

---

python/requirements.in
python/requirements.txt

Reverts uktrade/data-workspace-tools#234

Revert "adding pre-commit and boto3 to python base image"

---

deploy.sh

This PR adds a deployment script to be able to build and push tool images without the need of Jenkins

adding a deployment script

---

deploy.sh

Changed the tool argument entry from 'python-jupyerLab' to 'python-jupyterlab'.

fix: changed python jupyterlab to lower case

---

deploy.sh

Fixing image name for s3sync and metrics sidecar tools in build and deploy script.

fix build script - correct s3sync and metrics

---

python/requirements.txt
s3sync/requirements.txt

upgrading h11 to fix security vulnerability, https://github.com/uktrade/data-workspace-tools/security/dependabot

upgrading h11 to fix security vulnerability
