uktrade/data-workspace-tools

jupyterlab-python/Dockerfile, theia/Dockerfile
This was removed in https://github.com/uktrade/data-workspace/commit/114d9259377f30e4221109679d7523492a1264b6 since it wasn't being used. However, we've now had a request for it (for multiple users). It's fairly standard in the Data Science world, so let's have it back.
It should still play well with pip-based installs, so nothing _should_ break
Python 2 I think is a remnant of some older build of theia or node, so should be safe to remove
=> feat: add conda

rstudio/Dockerfile, rstudio/rstudio-start.sh
This is so we can have simpler code to connect to the datasets db from R. This is required since R does not seem to automatically inherit all parent environment variables.
=> feat: use libpq compatible env vars for db connection

theia/Dockerfile
When trying to bump Theia version, there are errors since it can't find ps. So installing now and seeing if it all works fine in the existing version to make the changes when later bumping Theia version smaller.
=> build(deps): include procps in Theia

theia/yarn.lock
- upgrade GOT to version 11.8.5
The GOT package before 11.8.5 and 12.1.0 for Node.js allows a redirect to a UNIX socket.
=> build(deps): upgrade-got-to-11.8.5

theia/package.json, theia/yarn.lock
Bump theia packages to 1.27.0 to fix vulnerability in @theia/git / moment.js
=> fix: bump theia packages to remove moment vulnerability

theia/package.json, theia/yarn.lock
Looks like a transitive dependency that is locked to an earlier version, so forcing the upgrade
DT-772
=> build(deps): upgrade socket.io-parser

theia/package.json, theia/yarn.lock
Also looks like no longer need to use "resolutions" on a few dependencies to force their versions
DT-972
=> build(deps): bump theia in order to bump engine.io

rstudio-rv4/Dockerfile, rstudio/Dockerfile
This unpins various packages, but we're still pinned to a major Debian version as well as v4 of R. I think this is probably good enough - pinning Debian packages more strongly tends to just give pain without I think much of a benefit.
=> feat: move to RStudio 4 in v4 Dockerfile

rstudio-rv4/Dockerfile
Suspect that the binary packages are only for Rv3 and so don't work.
=> feat: don't use cran-binary for Rv4

rstudio-rv4/Dockerfile
Requested by a user - to make it easier to use packages deployed to our GitLab instance
=> feat: install devtools by default in RStudio

rstudio-rv4/Dockerfile
Bump rstudio4 to fix the issue users were having with the `view()` function. This fixes it for one user who tested on staging.
=> fix: bump rstudio4 to 2023.03.0

jupyterlab-python/Dockerfile, rstudio-rv4/Dockerfile, rstudio/Dockerfile, theia/Dockerfile
Due to the moderate risk highlighted in the pen test report (9.2) the access to directory for all data workspace tools needs to be updated for both consistency and to ensure users do not have full access to the directory. The details of this report and the approach is listed below:
A review be carried out on the access control model for the affected "dw-install" binary, to ensure that users are not able to gain access to functionality they are not explicitly authorised to access.
A strong access control model helps prevent users accessing content, data or functionality for which they are not authorised. Errors in implementing the access control model could allow an attacker to perform vertical privilege escalation, where they are able to gain a higher level of access to the application …
=> fix: remove theia and jupyterhub full access to directory

pgadmin/Dockerfile, pgadmin/config_local.py, pgadmin/start.sh
- Switch pgadmin to a debian backed python image as the official alpine image causes issues with our dns proxy
-  Bump pgadmin to 7.8 (from 4.27)
=> feat: debian pgadmin4 7.8

theia/yarn.lock
This removes the "ip" npm package to avoid https://github.com/advisories/GHSA-78xj-cgh5-2h22. This is done just by upgrading dependancies using yarn.
=> build(deps): remove ip package, and update others

theia/package.json, theia/yarn.lock
This increases the version of msgpackr via resolutions to avoid https://github.com/advisories/GHSA-7hpj-7hhx-2fgx
It also tidies up what are now unnecessary resolutions.
This does change the minimum Theia version in package.json, but it doesn't actually change the version in the lock file.
=> build(deps): tidy resolutions and avoid msgpackr vulnerability

theia/Dockerfile, theia/package.json, theia/yarn.lock
This is to try to get it to build in Jenkins, because it's throwing `ERR_PACKAGE_PATH_NOT_EXPORTED`, and apparently that can be fixed by a new yarn version, which I'm hoping will get installed if we choose a more recent Debian which will clear caches.
=> build(deps): bump Debian, node, and force more resolutions in Theia

pgadmin/Dockerfile, pgadmin/start.sh
We see a lot of queries from pgAdmin's dashboard when looking at load on the database. It's hard to tell if they actually cause a problem, but turning them off by default should at least clear up a lot of noise.
This includes an increase of the version of pgAdmin just by the nature of  rebuilding with the latest version in PyPI. It's not pinned (it wasn't pinned before), but I suspect it increases the version from 7.8 to 8.3.
=> feat: disable dashboard from pgAdmin

s3sync/requirements.txt
This doesn't actually send to CloudWatch yet, but bumps to the version that can be configured to as a very small step
=> build(deps): bump mobius3 for code to log to CloudWatch

theia/Dockerfile
Some users seem to have a .profile in Theia and some don't, and often a .profile or a .bashrc file needs to be created before users have access to Conda. This change follows more up to date guidelines for system wide conda installs, which should result in the path being set properly, and then activates conda when theia is opened.
=> fix: correct conda install and activation in theia

rstudio-rv4/Dockerfile
Upgrading the rstudio-v4 base image to use debian bullseye, which would allow us to install PROJ 6.0, which would allow us to install sf > 1.0-14.
=> feat: rstudio4 on debian bullseye

rstudio-rv4/Dockerfile
Pin CRAN R version to 4.3.3 to alert future R upgrades in CRAN repo
=> fix: pin R version to 4.3.3

jupyterlab-python/Dockerfile, theia/Dockerfile
py39_4.11 defaults to python3.9.7 which is unfortunately a version that newer version of streamlit does not [support](https://github.com/streamlit/streamlit/blob/b15996cfc2b8a1d58035af11233f670a47cf9a7e/lib/setup.py#L109C1-L111C41).
Bumping the miniconda distribution to a newer version of python 3.9 for both jupyterlab and theia.
=> miniconda to py39_24.3.0

rstudio-rv4/Dockerfile
fix: rstudio session to load in new aws credentials when rstudio resets from an expired session
=> fix: force RProfile reload when rstudio resumes suspended session

pgadmin/config_local.py
I _think_ the timeout for getting connections is by default 10 seconds, and sometimes we get up to ~60 seconds. This should increase the connection timeout to 180 seconds.
Note I'm not 100% that this is even the right setting: it's an educated guess.
=> feat: speculatively increase pgAdmin connection timeout

mirrors-sync-cran-binary/Dockerfile, mirrors-sync-cran-binary/Dockerfile-rv4, mirrors-sync-cran-binary/build.R
This is a straight move of the CRAN binary code from data-workspace-frontend, so we can make further changes to it without it looking like we're changing the catalogue.
=> refactor: move CRAN binary code from data-workspace-frontend

s3sync/start.sh
This fixes the issue where windows would initially open but then refuse to open after some time. It also fixes an issue where the icons for Gretl and QGIS would disappear. And then also there are some speculative changes to stop cache/config files syncing - suspect they just take time and bandwidth and don't give much.
=> fix: don't sync various files between remote-desktop and S3 bucket

mirrors-sync-cran-binary/build.R
This are the ones we install in RStudio anyway (and it makes the rebuild of RStudio faster, and then allows people to upgrade quickly if necessary)
=> feat: more packages in the CRAN binary mirror

Dockerfile
We don't need it + we were only using it in one place + we can get ECS to do what it does if we want it
=> feat: remove tini

Dockerfile
The other steps seem to do this, so no need to do it twice
=> refactor: remove unnecessary plugin download step in Theia

Dockerfile, python-theia/package.json
Removing unnecessary step from Dockerfile - it's done via "prepare" which is run automatically by yarn install
=> refactor: remove unnecessary step from Dockerfile

python-theia/package.json
It was accidentally removed (and removing duplicate download/build)
=> fix: restore Theia postgres

Dockerfile
We have a new bucket area for DDaT data science packages to be added from Gitlab. This change should make pip install look in this bucket area for packages as well as the mirror bucket
=> feat: add new private package index to dockerfile

Dockerfile, rv4-rstudio/dw-rstudio-in-rstudio
There are a few use cases where it's helpful to have multiple RStudios, e.g. to have multiple interactive consoles at once. While maybe a bit odd, we can leverage Data Workspace's "--9000" system for developing visualisations for running an RStudio from inside RStudio.
=> feat: add basic dw-rstudio-in-rstudio script

Dockerfile
This has been requested by a user to make it easier to compile/"knit" R Markdown files from RStudio.
While we can't add everything to the base image, since the UI in RStudio offers specific rmarkdown features, think it's reasonable to add rmarkdown.
=> feat: add rmarkdown to R base image(s)

Dockerfile
Although we now have rmarkdown package installed, it looks like some R Markdown features in RStudio also need the markdown package installed.
=> feat: add markdown to R base image(s)

Dockerfile
It was requested to add Roboto to RStudio since it's recommended by GDS, and there was light talk of adding others to experiment with. Suspect reasonable to add all of Debian's recommended fonts.
=> feat: add fonts to all images

Dockerfile
Tweaking the previous change that installed fonts right on the base base image, and moving them to where users could actually use them - for clarity and space reasons.
=> feat: install fonts only on images needed

Jenkinsfile
There is an existing "vscode" repo in ECR, and not "vs-code" and we can/should use the existing one without a dash (it was setup for experimentation, which is fine for us to now use proper).
=> fix: use existing "vscode" ECR repo

Dockerfile, python-vscode/settings.json, python-vscode/start.sh
Similar to other python-theia, we activate conda when launching a bash login shell (which needs VS Code specific configuration to start).
Python notebooks are enabled by installing the relevant extensions
Getting Python notebooks working requires a modification to the VS Code / code-server codebase, to rewrite domains that request resources under subdomains of vscode-cdn.net to an invalid domain. This rewrite allows us to open up the CSP on data workspace to this invalid domain, without actually increasing the risk of data leakage. The reason why this actually helps is because VS Code has service workers that intercept such requests and responds with the correct content served internally, without communicating with the internet.
=> feat: conda and Python notebooks working in VS Code

Dockerfile
Fixing a typo - the version before this change does not exist
=> fix: VSCode Jupyter extension version

Dockerfile, python-jupyterlab/jupyter_notebook_config.py
This is done for 2 reasons
- Purely user-facing to have a more consistent experience
- For the upcoming move to bookworm - it more strongly forbids install of Python packages in the root environment except those that can be installed through apt install. So suspect that all packages will have to managed by conda in all tools.
=> feat: consistently activate conda in all Python tools

Dockerfile
This activates conda inside the Dockerfile, so Python packages are installed into a conda environment/virtual environment.
This is to ease our move to bookworm, where it strictly forbids pip install of packages.
=> feat: install Python packages with conda

Dockerfile
In order to move to Debian bookworm, which is stricter in terms of not installing Python packages in the root env that are not Debian-y, we need to install package always via a virtual environment.
In a previous change I thought we did this for s3sync, but I placed the "activate" in the wrong RUN part of the Dockerfile.
=> refactor: really install s3sync in venv

python/requirements.in, python/requirements.txt
This makes it easier for people to pip-compile requirements.in files (and I suspect was possible out of the box before we made the conda base environment activated everywhere - it would have been installed as package in the Python that came with Debian)
=> feat: include pip-tools in conda base environment

Dockerfile
The users don't need to see role and tablespaces in pgAdmin to do data analysis, so this makes the pgAdmin interface just that tiny bit clearer. And in fact, since we have many thousands of roles, there are even performance implications of trying to fetch all the roles, so we should hopefully save some user/db time from not showing them.
=> feat: hide role and tablespace nodes in pgAdmin

Dockerfile
For some reason pgAdmin continues to try to fetch roles from the database, which is really slow, even though they are no longer visible in the UI. As a workaround, adding a LIMIT 0 to the query that fetches them _should_ make it much more performant, while (hopefully) not causing anything to break.
=> fix: avoid slow query fetching roles from database

Dockerfile, python-vscode/settings.json
We use theia-postgres in Theia, so this is a step towards feature parity between the two, in order to eventually remove Theia.
As described in the comment in the Dockerfile, vscode-postgres doesn't have an out-of-the-box way of automatically configuring the connection, so we monkey-patch it do so
=> feat: add vscode-postgres to VSCode

python/requirements.txt
This upgrades the version of 'hypercorn' from 0.14.4 to 0.17.3 to avoid CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-44487.
=> build: upgraded hypercorn

Jenkinsfile
Configmap was changed to secret when EKS cluster was rebuilt as it contained credentials.
=> Update Jenkinsfile to use new Kubernetes secret

Dockerfile
After some issues with data being stored where it shouldn't be, we have some documentation for deleting data and rewriting history. This always involves installing git-filter-repo, so installing it on the Python base image means we can skip a step in these docs
=> feat: install git filter repo on python base

Dockerfile, python-vscode/merge-settings.py, python-vscode/start.sh
This moves the user-data-dir for VS Code (via code-server) into the home directory, which contains VS Code gets persisted to S3 and so preserves settings between launches.
There are 2 complications to this however:
- We do need to enforce a few initial/default settings. There doesn't seem to be a built-in way of doing this, so a custom Python script is included that merges the default settings with the user's. We always override the users with the initial/default. Maybe down the line this would need to be more intelligent to allow users to change some of the initial settings.
- The extensions directory is by default part of user-data-dir, but we also need to include a list of initial/default extensions that users should not be able to remove. So for now it is configured outside of the …
=> feat: ability for VS Code settings to persist

Dockerfile
It seems this command is needed in order to use glfsm to download hugginface models without just downloading the pointers. Putting it into the dockerfile to make this easier for users
=> fix: initialise LFS in python tools

Dockerfile
It seems that within the conda env less isn't available, meaning that running some basic git commands such as git branch -a don't work unless you deactivate the env. Putting it in the image now to make things easier for users
=> fix: conda install less

Dockerfile
There is at least one package being used within Rstudio that needs CMake and user would rather not have to install this on every boot of the tool. Installing in the image instead to make this process nicer and maybe support other packages that use Cmake in future
=> feat: install cmake in R images

Dockerfile
not sure what the issue is yet, but since this Rstudio instances aren't starting, removing to test on staging before trying again
=> revert: remove cmake from r images
